[config]

[templates.obsidian]
input_path = "/home/felix/.config/matugen/templates/obsidian-colors.css"
output_path = "/home/felix/Uni/.obsidian/themes/Matugen/theme.css"

[templates.rofi]
input_path = "/home/felix/.config/matugen/templates/rofi-colors.rasi"
output_path = "/home/felix/.config/rofi/rofi-colors.rasi"

[templates.spicetify]
input_path = "/home/felix/.config/matugen/templates/spicetify.ini"
output_path = "/home/felix/.config/spicetify/Themes/Comfy/color.ini"
post_hook = 'spicetify apply'

[templates.drift]
input_path = "/home/felix/.config/matugen/templates/drift.toml"
output_path = "/home/felix/.config/drift/config.toml"

[templates.starship]
input_path = "/home/felix/.config/matugen/templates/starship.toml"
output_path = "/home/felix/.config/starship.toml"

[templates.superfile]
input_path = "/home/felix/.config/matugen/templates/superfile.toml"
output_path = "/home/felix/.config/superfile/theme/matugen.toml"

[templates.ratty]
input_path = "/home/felix/.config/matugen/templates/ratty.toml"
output_path = "/home/felix/.config/ratty/ratty.toml"
