-- Autogenerated by Hellwal
local theme = {}

-- Background & foreground
theme.bg_normal = "#%%background.hex%%"
theme.bg_focus = "#%%color2.hex%%"
theme.bg_urgent = "#%%color1.hex%%"
theme.bg_minimize = "#%%color8.hex%%"
theme.bg_systray = theme.bg_normal

theme.fg_normal = "#%%foreground.hex%%"
theme.fg_focus = "#%%color15.hex%%"
theme.fg_urgent = "#%%color7.hex%%"
theme.fg_minimize = "#%%color6.hex%%"

-- Borders
theme.border_width = 2
theme.border_normal = "#%%color0.hex%%"
theme.border_focus = "#%%foreground.hex%%"
theme.border_marked = "#%%color3.hex%%"

-- Titlebars
theme.titlebar_bg_normal = "#%%background.hex%%"
theme.titlebar_bg_focus = "#%%color0.hex%%"
theme.titlebar_fg_focus = "#%%color15.hex%%"
theme.titlebar_fg_normal = "#%%foreground.hex%%"

-- Taglist
theme.taglist_fg_focus = "#%%color15.hex%%"
theme.taglist_bg_focus = "#%%color2.hex%%"
theme.taglist_fg_urgent = "#%%color1.hex%%"
theme.taglist_bg_urgent = "#%%color0.hex%%"
theme.taglist_fg_occupied = "#%%color7.hex%%"
theme.taglist_bg_occupied = "#%%background.hex%%"
theme.taglist_fg_empty = "#%%color8.hex%%"
theme.taglist_bg_empty = "#%%background.hex%%"

-- Tasklist
theme.tasklist_bg_focus = "#%%color0.hex%%"
theme.tasklist_fg_focus = "#%%color15.hex%%"

return theme
